django_test/django_test/urls.py
from django.conf.urls import url
from django.contrib import admin
admin.autodiscover()
import blog.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/index/(?P<id>\d{2})$', blog.views.index),
    url(r'^blog/index1/(?P<id>\d{2})$', blog.views.index1),
    url(r'^blog/index2/(?P<id>\d{2})$', blog.views.index2),
    url(r'^blog/db/(?P<type>\d{1})$', blog.views.db_ctrl),
#     
    url(r'^upload/(?P<type>\d{1})$', blog.views.upload),
#     
    url(r'^reg$', blog.views.reg),
    url(r'^login$', blog.views.login),
    url(r'^showUser$', blog.views.showUser),
    url(r'^logout$', blog.views.logout),
]

django_test/blog/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from random import choice
from ptools.global_data import tGlobalData

sex_choices = (
    ('f', '女'),
    ('m', '男'),
)

class Entry(models.Model):
    name = models.CharField(max_length=128)
#     data = models.CharField(max_length=1024)
    def __unicode__(self):
        return self.name
    
# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=128)
    entry = models.ForeignKey(Entry)
    
    def __unicode__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=128)
    addr = models.CharField(max_length=256)
    age = models.CharField(max_length=4)
    sex = models.CharField(max_length=4, choices=sex_choices)
    passwd = models.CharField(max_length=128)
     
    def __unicode__(self):
        return self.name + "\t" + self.addr + "\t" + self.age + "\t" + self.sex + "\t" + self.passwd

class Author(models.Model):
    name = models.CharField(max_length=128)
    
    def __unicode__(self):
        return self.name
    
class Book(models.Model):
    name = models.CharField(max_length=128)
    autours = models.ManyToManyField(Author)

    def __unicode__(self):
        return self.name

class UserForm(models.Model):
    name = models.CharField(max_length=64)
    age = models.IntegerField()
    img = models.FileField(upload_to=tGlobalData.PROJECT_PATH + '/recv/')

    def __unicode__(self):
        return self.name + " 上传"

django_test/blog/views.py
# coding=utf-8
from blog.base import base_pages
from blog.db import ctrl_db
from django.template.base import Template
from django.template.context import Context
from django.http.response import HttpResponse
import traceback
from blog.reg import upload_test, reg_test
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(req, id):
    return base_pages.index(req, id)

# Create your views here.
def index1(req, id):
    return base_pages.index1(req, id)

# Create your views here.
def index2(req, id):
    return base_pages.index2(req, id)

def db_ctrl(req, type):
    sType = type + ''
    try :
        if 0 == cmp(sType, '1') :
            res = ctrl_db.db_ins()
        elif 0 == cmp(sType, '2') :
            res = ctrl_db.db_n2_1()
        elif 0 == cmp(sType, '3') :
            res = ctrl_db.db_n2_n()
        elif 0 == cmp(sType, '4') :
            res = ctrl_db.db_sel()
        elif 0 == cmp(sType, '5') :
            res = ctrl_db.db_del()
        elif 0 == cmp(sType, '6') :
            res = ctrl_db.db_upd()
        else :
            res = HttpResponse('<h1>Input Error</h1>')
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res


@csrf_exempt
def upload(req,type):
    sType = type + ''
    try :
        if 0 == cmp(sType, '0') :
            res = upload_test.upfile(req)
        elif 0 == cmp(sType, '1') :
            res = upload_test.upfile1(req)
        else :
            res = HttpResponse('<h1>Input Error</h1>')
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res

@csrf_exempt
def reg(req):
    try :
        res = reg_test.reg(req)
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res

@csrf_exempt
def login(req):
    try :
        res = reg_test.login(req)
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res

@csrf_exempt
def showUser(req):
    try :
        res = reg_test.showUser(req)
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res

@csrf_exempt
def logout(req):
    try :
        res = reg_test.logout(req)
    except :
        res = HttpResponse('<h1>Data Error</h1>')
        traceback.print_exc() 
        
    return res

django_test/blog/templates/index.html
<html>

<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>{{ title }}</title>
</head>


<body>
打印单项<br/>
hello : {{ user.name }}<br/>
say : {{ user1.say }}<br/>
{{ book_list.0 }}<br/>

if<br/>
{% if id < 100 %}
    id : {{ id }} <br/>
{% else %}
    id 小于10 <br/>
{% endif %}

for<br/>
{% for book in book_list %}
    book : {{ book }} <br/>
{% endfor %}

K,V<br/>
{% for k,v in user.items %}
    {{ forloop.counter }}.{{ k }} : {{ v }} <br/>
{% endfor %}

</body>

</html>

django_test/blog/templates/reg.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>注册</title>
</head>
<body class="body">
	<form method="post" enctype="multipart/form-data">{% csrf_token %}
		{{uf}}
		<input type="submit" value="注册"/>
	</form>
</body>
</html>

django_test/blog/templates/reg1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>注册</title>
</head>
<body class="body">
	<form method="post" enctype="multipart/form-data">{% csrf_token %}
		<label for="id_name">姓名</label><input type="text" name="name"><br/>
		<label for="id_age">年龄</label><input type="text" name="age"><br/>
		<label for="id_img">年龄</label><input type="file" name="img"><br/>
		<input type="submit" value="OK"/>
	</form>
</body>
</html>

django_test/blog/templates/reg_user.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>注册</title>
</head>
<body class="body">
	<form method="post" enctype="multipart/form-data">{% csrf_token %}
		{{pf}}
		<input type="submit" value="OK"/>
	</form>
</body>
</html>

django_test/blog/templates/sel_res.html
<html>

<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>{{title}}</title>
</head>


<body>
	{% for person in persons %}
		 {{forloop.counter}}.{{person.name}}:{{person.addr}}<br/>
	{% endfor%}
	ALL<br/>
	{% for person in persons %}
		 {{forloop.counter}}.{{person}}<br/>
	{% endfor%} 
	共有{{len}}条记录
</body>

</html>